# Generated by Django 4.1.5 on 2023-02-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecievedSMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.IntegerField()),
                ("message", models.CharField(max_length=256)),
                ("sender", models.CharField(max_length=20)),
                ("linkId", models.CharField(blank=True, max_length=200, null=True)),
                ("short_code", models.CharField(blank=True, max_length=10, null=True)),
                ("date", models.DateTimeField()),
            ],
            options={
                "verbose_name": "recievedsms",
                "verbose_name_plural": "recievedsmss",
            },
        ),
        migrations.CreateModel(
            name="SentSMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.CharField(max_length=20)),
                ("message", models.CharField(max_length=256)),
                ("short_code", models.CharField(blank=True, max_length=10, null=True)),
                ("enqueue", models.BooleanField(blank=True, default=True, null=True)),
                ("keyword", models.CharField(blank=True, max_length=100, null=True)),
                ("linkId", models.CharField(blank=True, max_length=200, null=True)),
                ("date", models.DateTimeField(auto_now=True)),
                ("cost", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "request_status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (100, "Processed"),
                            (101, "Sent"),
                            (102, "Queued"),
                            (401, "RiskHold"),
                            (402, "InvalidSenderId"),
                            (403, "InvalidPhoneNumber"),
                            (404, "UnsupportedNumberType"),
                            (406, "UserInBlacklist"),
                            (407, "CouldNotRoute"),
                            (500, "InternalServerError"),
                            (501, "GatewayError"),
                            (502, "RejectedByGateway"),
                        ],
                        null=True,
                    ),
                ),
                ("sms_status", models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                "verbose_name": "sent_sms",
                "verbose_name_plural": "sent_sms",
            },
        ),
    ]
