# Generated by Django 4.1.5 on 2023-02-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BulkRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        choices=[
                            (100, "Processed"),
                            (101, "Sent"),
                            (102, "Queued"),
                            (401, "RiskHold"),
                            (402, "InvalidSenderId"),
                            (403, "InvalidPhoneNumber"),
                            (404, "UnsupportedNumberType"),
                            (406, "UserInBlacklist"),
                            (407, "CouldNotRoute"),
                            (500, "InternalServerError"),
                            (501, "GatewayError"),
                            (502, "RejectedByGateway"),
                        ]
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("cost", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=50)),
                ("message_id", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Bulk Recipient",
                "verbose_name_plural": "Bulk Recipients",
            },
        ),
        migrations.CreateModel(
            name="BulkSMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipients", models.TextField()),
                ("message", models.CharField(max_length=256)),
                (
                    "short_code",
                    models.CharField(
                        blank=True, default="AFRICASTKNG", max_length=50, null=True
                    ),
                ),
                ("enqueue", models.BooleanField(blank=True, default=True, null=True)),
                ("keyword", models.CharField(blank=True, max_length=100, null=True)),
                ("link_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "response_message",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "response_recipients",
                    models.ManyToManyField(blank=True, to="aft_sms.bulkrecipient"),
                ),
            ],
            options={
                "verbose_name": "Bulk Sms",
                "verbose_name_plural": "Bulk Sms",
            },
        ),
    ]
