# Generated by Django 4.1.5 on 2023-02-02 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="B2CEntries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("InvalidRequest", "InvalidRequest"),
                            ("Failed", "Failed"),
                            ("NotSupported", "NotSupported"),
                            ("Queued", "Queued"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("provider", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "provider_channel",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("value", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "transaction_fee",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
            options={
                "verbose_name": "B2CEntries",
                "verbose_name_plural": "B2CEntries",
            },
        ),
        migrations.CreateModel(
            name="B2CRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("phone_number", models.CharField(max_length=50)),
                ("currency", models.CharField(max_length=5)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "provider_channel",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BusinessPayment", "BusinessPayment"),
                            (
                                "SalaryPaymentWithWithdrawalChargePaid",
                                "SalaryPaymentWithWithdrawalChargePaid",
                            ),
                            (
                                "BusinessPaymentWithWithdrawalChargePaid",
                                "BusinessPaymentWithWithdrawalChargePaid",
                            ),
                            ("SalaryPayment", "SalaryPayment"),
                            ("PromotionPayment", "PromotionPayment"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "B2CRecipient",
                "verbose_name_plural": "B2CRecipients",
            },
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("bank_account_name", models.CharField(max_length=100)),
                ("bank_account_no", models.CharField(max_length=50)),
                ("bank_account_code", models.IntegerField()),
                (
                    "bank_account_DOB",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("currency_code", models.CharField(max_length=5)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("narration", models.CharField(max_length=250)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("InvalidRequest", "InvalidRequest"),
                            ("Failed", "Failed"),
                            ("NotSupported", "NotSupported"),
                            ("Queued", "Queued"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "bank",
                "verbose_name_plural": "banks",
            },
        ),
        migrations.CreateModel(
            name="BTRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_account_name", models.CharField(max_length=100)),
                ("bank_account_no", models.CharField(max_length=50)),
                ("bank_account_code", models.IntegerField()),
                (
                    "bank_account_DOB",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("currency_code", models.CharField(max_length=5)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("narration", models.CharField(max_length=250)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "banktransferrecipient",
                "verbose_name_plural": "banktransferrecipients",
            },
        ),
        migrations.CreateModel(
            name="BTResponseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("InvalidRequest", "InvalidRequest"),
                            ("Failed", "Failed"),
                            ("NotSupported", "NotSupported"),
                            ("Queued", "Queued"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_fee",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "btresponseentry",
                "verbose_name_plural": "btresponseentrys",
            },
        ),
        migrations.CreateModel(
            name="BusinessToBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("TigoTanzania", "TigoTanzania"),
                            ("Athena", "Athena"),
                            ("Mpesa", "Mpesa"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        default="BusinessToBusinessTransfer", max_length=100
                    ),
                ),
                ("currency_code", models.CharField(max_length=5)),
                ("amount", models.CharField(max_length=150)),
                ("destination_channel", models.CharField(max_length=100)),
                ("destination_account", models.CharField(max_length=100)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("InvalidRequest", "InvalidRequest"),
                            ("Failed", "Failed"),
                            ("NotSupported", "NotSupported"),
                            ("Queued", "Queued"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_fee",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "provider_channel",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "B2B",
                "verbose_name_plural": "B2B",
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("cvv_number", models.IntegerField()),
                ("expiry_month", models.IntegerField()),
                ("expiry_year", models.IntegerField()),
                ("country_code", models.CharField(max_length=2)),
                ("auth_token", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "card",
                "verbose_name_plural": "cards",
            },
        ),
        migrations.CreateModel(
            name="CustomerToBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                (
                    "provider_channel",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone_number", models.IntegerField()),
                ("currency_code", models.CharField(max_length=5)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("InvalidRequest", "InvalidRequest"),
                            ("Failed", "Failed"),
                            ("NotSupported", "NotSupported"),
                            ("PendingConfirmation", "PendingConfirmation"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("provider", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "C2B",
                "verbose_name_plural": "C2B",
            },
        ),
        migrations.CreateModel(
            name="TopupStash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("currency_code", models.CharField(max_length=3)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("metadata", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Failed", "Failed"), ("Success", "Success")],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "topupstash",
                "verbose_name_plural": "topupstashs",
            },
        ),
        migrations.CreateModel(
            name="WalletTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("targetProductCode", models.IntegerField()),
                ("currency_code", models.CharField(max_length=3)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("metadata", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Failed", "Failed"), ("Success", "Success")],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "wallettransfer",
                "verbose_name_plural": "wallettransfers",
            },
        ),
        migrations.CreateModel(
            name="CardCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                (
                    "checkout_token",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("currency_code", models.CharField(max_length=3)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("narration", models.CharField(max_length=250)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Failed", "Failed"),
                            ("NotSupported", "NotSupported"),
                            ("Success", "Success"),
                            ("PendingConfirmation", "PendingConfirmation"),
                            ("InvalidRequest", "InvalidRequest"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "payment_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aft_payment.card",
                    ),
                ),
            ],
            options={
                "verbose_name": "cardcheckout",
                "verbose_name_plural": "cardcheckout",
            },
        ),
        migrations.CreateModel(
            name="BusinessToCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("number_queued", models.IntegerField(blank=True, null=True)),
                (
                    "total_value",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("entries", models.ManyToManyField(to="aft_payment.b2centries")),
                ("recipients", models.ManyToManyField(to="aft_payment.b2crecipient")),
            ],
            options={
                "verbose_name": "B2C",
                "verbose_name_plural": "B2C",
            },
        ),
        migrations.CreateModel(
            name="BankTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("entries", models.ManyToManyField(to="aft_payment.btresponseentry")),
                ("recipients", models.ManyToManyField(to="aft_payment.btrecipient")),
            ],
            options={
                "verbose_name": "banktransfer",
                "verbose_name_plural": "banktransfers",
            },
        ),
    ]
